version: '2'
services:
    nuochong-app:
        image: nuochong
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://nuochong-mysql:3306/nuochong?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    nuochong-mysql:
        extends:
            file: mysql.yml
            service: nuochong-mysql
